/**
 * Recettes marocaines pour Oriental Boucherie
 * Chaque recette met en valeur un type de viande différent et est prête pour l'importation dans Sanity
 */

export const moroccanRecipes = [
  {
    _type: "recipe",
    title: "Couscous traditionnel",
    slug: { _type: "slug", current: "couscous-traditionnel" },
    mainImage: { _type: "image", asset: { _type: "reference", _ref: "image-placeholder-couscous" } },
    country: "Maroc",
    publishedAt: new Date().toISOString(),
    prepTime: 45,
    cookTime: 120,
    servings: 4,
    ingredients: [
      { ingredient: "Smen ou beurre clarifié", amount: "100 g" },
      { ingredient: "Pois chiches", amount: "125 g" },
      { ingredient: "Morceaux d'agneau", amount: "500 g" },
      { ingredient: "Semoule de couscous", amount: "500 g" },
      { ingredient: "Raisins blonds", amount: "60 g" },
      { ingredient: "Huile d'olive", amount: "1 c.à.s" },
      { ingredient: "Tranches de jarret de veau", amount: "½" },
      { ingredient: "Ail", amount: "3 gousses" },
      { ingredient: "Oignon", amount: "1" },
      { ingredient: "Tomate ou concentré de tomate", amount: "1" },
      { ingredient: "Navets", amount: "4" },
      { ingredient: "Carottes", amount: "4" },
      { ingredient: "Brins de coriandre", amount: "Au goût" },
      { ingredient: "Branche de céleri", amount: "1" },
      { ingredient: "Courgettes", amount: "4" },
      { ingredient: "Ras-el-hanout", amount: "Au goût" },
      { ingredient: "Mélange à couscous prêt", amount: "Au goût" },
      { ingredient: "Persil haché", amount: "Au goût" }
    ],
    steps: [
      { title: "Chauffer la matière grasse", description: "Fondre le smen ou le beurre dans le fond du couscoussier." },
      { title: "Dorer les viandes", description: "Saisir l'agneau et le veau coupés, puis réserver hors du feu." },
      { title: "Cuire les légumes", description: "Faire revenir l'oignon, ajouter légumes et épices et cuire quelques minutes." },
      { title: "Mijoter longuement", description: "Remettre les viandes, couvrir d'eau, saler, poivrer, couvrir et laisser mijoter 1 h." },
      { title: "Gonfler la semoule", description: "Verser de l'eau bouillante sur la semoule, mélanger et laisser reposer 30 min." },
      { title: "Cuisson vapeur", description: "Cuire la semoule à la vapeur dans le couscoussier pendant 15 min." },
      { title: "Assemblage final", description: "Ajouter raisins et persil, terminer la cuisson 10 min puis servir bien chaud." }
    ],
    description: "Un couscous parfumé où viandes et légumes mijotent doucement, sublimés par une semoule moelleuse et arômes orientaux.",
    body: [],
    featured: false,
    relatedProducts: []
  },
  {
    _type: "recipe",
    title: "Tajine de poulet aux olives et citrons confits",
    slug: { _type: "slug", current: "tajine-poulet-olives-citrons-confits" },
    mainImage: { _type: "image", asset: { _type: "reference", _ref: "image-placeholder-tajine-poulet" } },
    country: "Maroc",
    publishedAt: new Date().toISOString(),
    prepTime: 20,
    cookTime: 105,
    servings: 4,
    ingredients: [
      { ingredient: "Oignons finement émincés", amount: "2" },
      { ingredient: "Citrons confits", amount: "2" },
      { ingredient: "Gingembre moulu", amount: "1 c.à.c" },
      { ingredient: "Curcuma", amount: "1 c.à.c" },
      { ingredient: "Cumin moulu", amount: "1 c.à.c" },
      { ingredient: "Coriandre fraîche ciselée", amount: "4 c.à.s" },
      { ingredient: "Sel et poivre", amount: "Au goût" },
      { ingredient: "Morceaux de poulet", amount: "1 poulet entier coupé" },
      { ingredient: "Ail en chemise", amount: "5 gousses" },
      { ingredient: "Jus de citron", amount: "1 citron" },
      { ingredient: "Olives vertes dénoyautées", amount: "400 g" },
      { ingredient: "Huile d'argan (ou d'olive)", amount: "3 c.à.s" },
      { ingredient: "Eau", amount: "20 cl" }
    ],
    steps: [
      { title: "Suer les aromatiques", description: "Chauffer l'huile, faire revenir oignons et deux gousses d'ail jusqu'à légère coloration." },
      { title: "Colorer le poulet", description: "Assaisonner et saisir les morceaux de poulet sur toutes les faces." },
      { title: "Ajouter épices et liquides", description: "Incorporer épices, jus de citron, eau et ail restant." },
      { title: "Cuisson au four", description: "Couvrir et cuire 1 h à 150 °C." },
      { title: "Incorporez olives et citrons", description: "Retirer, ajouter olives, quartiers de citron et coriandre." },
      { title: "Finir la cuisson", description: "Replacer au four 30 min puis servir accompagné de semoule." }
    ],
    description: "Tajine de poulet mijoté aux olives et citrons confits, relevé par un bouquet d'épices chaudes et relevées.",
    body: [],
    featured: false,
    relatedProducts: []
  },
  {
    _type: "recipe",
    title: "Ojja tunisienne aux merguez",
    slug: { _type: "slug", current: "ojja-tunisienne-aux-merguez" },
    mainImage: { _type: "image", asset: { _type: "reference", _ref: "image-placeholder-ojja-merguez" } },
    country: "Tunisie",
    publishedAt: new Date().toISOString(),
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    ingredients: [
      { ingredient: "Merguez bien dorées", amount: "4 à 6" },
      { ingredient: "Oignon haché", amount: "1" },
      { ingredient: "Poivrons verts en lanières", amount: "1 à 2" },
      { ingredient: "Tomates en dés", amount: "2 à 4" },
      { ingredient: "Ail émincé", amount: "2 à 4 gousses" },
      { ingredient: "Œufs", amount: "4" },
      { ingredient: "Concentré de tomates", amount: "2 c.à.s" },
      { ingredient: "Huile d'olive", amount: "2 c.à.s" },
      { ingredient: "Harissa", amount: "1 c.à.c" },
      { ingredient: "Cumin", amount: "1 c.à.c" },
      { ingredient: "Paprika", amount: "1 c.à.c" },
      { ingredient: "Sel et poivre", amount: "Au goût" },
      { ingredient: "Persil frais", amount: "Pour garnir" },
      { ingredient: "Carvi et coriandre moulue", amount: "Facultatif" }
    ],
    steps: [
      { title: "Dorer les merguez", description: "Saisir les saucisses dans l'huile chaude jusqu'à coloration, réserver." },
      { title: "Fondre les légumes", description: "Dans la même poêle, cuire oignon, poivrons et ail jusqu'à tendreté." },
      { title: "Rouiller les tomates", description: "Ajouter tomates et laisser réduire 10 min." },
      { title: "Assaisonner", description: "Incorporer concentré, épices et harissa, mijoter 5 min." },
      { title: "Braiser les œufs", description: "Remettre merguez, créer des nids pour les œufs, couvrir et cuire 5–7 min." },
      { title: "Décorer et servir", description: "Parsemer de persil et déguster chaud." }
    ],
    description: "Ojja tunisienne épicée mélangeant merguez, légumes et œufs, relevée par la chaleur de la harissa.",
    body: [],
    featured: false,
    relatedProducts: []
  },
  {
    _type: "recipe",
    title: "Tajine de keftas aux œufs",
    slug: { _type: "slug", current: "tajine-de-keftas-aux-oeufs" },
    mainImage: { _type: "image", asset: { _type: "reference", _ref: "image-placeholder-tajine-keftas" } },
    country: "Maroc",
    publishedAt: new Date().toISOString(),
    prepTime: 15,
    cookTime: 30,
    servings: 6,
    ingredients: [
      { ingredient: "Viande hachée parfumée", amount: "1 kg" },
      { ingredient: "Œufs", amount: "6" },
      { ingredient: "Tomates concassées", amount: "500 g" },
      { ingredient: "Oignon émincé", amount: "250 g" },
      { ingredient: "Concentré de tomates", amount: "4 c.à.c" },
      { ingredient: "Cumin", amount: "1 c.à.c" },
      { ingredient: "Paprika doux", amount: "1 c.à.c" },
      { ingredient: "Poivre blanc", amount: "1 pincée" },
      { ingredient: "Gingembre en poudre", amount: "1 pincée" },
      { ingredient: "Safran", amount: "1 pincée" },
      { ingredient: "Cannelle", amount: "1 pincée" },
      { ingredient: "Sel", amount: "1 pincée" },
      { ingredient: "Persil ou coriandre hachée", amount: "2 c.à.c" },
      { ingredient: "Huile d'olive", amount: "10 cl" },
      { ingredient: "Eau", amount: "20 cl" },
      { ingredient: "Ras-el-hanout", amount: "Au goût" }
    ],
    steps: [
      { title: "Façonner les keftas", description: "Assaisonner la viande, former des boulettes régulières en incorporant ras-el-hanout." },
      { title: "Préparer la base", description: "Dans le tajine, réunir oignon et tomates, verser huile et eau, mijoter 5 min." },
      { title: "Ajouter les boulettes", description: "Plonger les keftas, couvrir et laisser cuire 20 min à feu moyen." },
      { title: "Pocher les œufs", description: "Creuser des puits, casser les œufs, couvrir et cuire jusqu'à prise des blancs." },
      { title: "Finaliser et servir", description: "Saupoudrer de persil et servir immédiatement." }
    ],
    description: "Tajine marocain où des boulettes épicées mijotent avec des œufs pochés dans une sauce onctueuse.",
    body: [],
    featured: false,
    relatedProducts: []
  },
  {
    _type: "recipe",
    title: "Molokheya à la tunisienne",
    slug: { _type: "slug", current: "molokheya-a-la-tunisienne" },
    mainImage: { _type: "image", asset: { _type: "reference", _ref: "image-placeholder-molokheya" } },
    country: "Tunisie",
    publishedAt: new Date().toISOString(),
    prepTime: 20,
    cookTime: 270,
    servings: 4,
    ingredients: [
      { ingredient: "Huile d'olive", amount: "100 ml" },
      { ingredient: "Bœuf à braiser", amount: "750 g" },
      { ingredient: "Oignon haché", amount: "1" },
      { ingredient: "Ail", amount: "6 à 7 gousses" },
      { ingredient: "Feuilles de laurier", amount: "2 à 3" },
      { ingredient: "Harissa", amount: "1 c.à.c" },
      { ingredient: "Poudre de molokheya", amount: "100 g" },
      { ingredient: "Ras-el-hanout (ou coriandre+carvi)", amount: "1 c.à.s ou 1 c.à.c+1 c.à.c" },
      { ingredient: "Eau bouillante", amount: "Jusqu'à 3/4 du récipient" }
    ],
    steps: [
      { title: "Faire bouillir l'eau", description: "Porter une grande quantité d'eau à ébullition." },
      { title: "Dorer oignon et viande", description: "Dans une cocotte, chauffer l'huile, saisir l'oignon, ajouter la viande et dorer." },
      { title: "Incorporer la molokheya", description: "Saupoudrer la poudre, mélanger pour obtenir une pâte épaisse." },
      { title: "Ajouter l'eau progressivement", description: "Remettre sur feu doux, verser l'eau bouillante en fouettant pour éviter les grumeaux, cuire 1 h." },
      { title: "Parfumer et mijoter", description: "Ajouter ail, laurier, harissa et épices, saler, laisser mijoter 2–3 h à feu très doux." },
      { title: "Vérifier la cuisson", description: "La molokheya est prête lorsque l'huile remonte à la surface et la viande est tendre." },
      { title: "Servir chaud", description: "Accompagner de pain tunisien ou de riz selon préférence." }
    ],
    description: "Velouté traditionnel tunisien où la poudre de molokheya se mêle à la viande de bœuf et aux épices pour un plat réconfortant.",
    body: [],
    featured: false,
    relatedProducts: []
  },
  {
    _type: "recipe",
    title: "Tanjia marrakchia",
    slug: { _type: "slug", current: "tanjia-marrakchia" },
    mainImage: { _type: "image", asset: { _type: "reference", _ref: "image-placeholder-tanjia" } },
    country: "Maroc",
    publishedAt: new Date().toISOString(),
    prepTime: 20,
    cookTime: 180,
    servings: 6,
    ingredients: [
      { ingredient: "Jarret de mouton", amount: "2 kg" },
      { ingredient: "Citron confit", amount: "1" },
      { ingredient: "Huile d'olive", amount: "20 cl" },
      { ingredient: "Cumin", amount: "1 c.à.s" },
      { ingredient: "Curcuma", amount: "1 c.à.s" },
      { ingredient: "Ail écrasé", amount: "4 gousses" },
      { ingredient: "Ail entier", amount: "4 gousses" },
      { ingredient: "Smen", amount: "1 c.à.c" },
      { ingredient: "Ras-el-hanout", amount: "1 c.à.c" },
      { ingredient: "Safran", amount: "0,5 c.à.c" },
      { ingredient: "Sel", amount: "0,5 c.à.c" },
      { ingredient: "Eau", amount: "300 ml" }
    ],
    steps: [
      { title: "Mariner la viande", description: "Éplucher et écraser 4 gousses d'ail, laisser les autres entières. Mélanger avec la viande, citron confit, sel, épices, smen puis réfrigérer 15 min." },
      { title: "Cuisson initiale", description: "Déposer la viande et l'ail mariné dans une cocotte, ajouter eau et huile puis couvrir." },
      { title: "Mijotage prolongé", description: "Cuire à feu très doux 3 h, en ajoutant de l'eau si nécessaire, jusqu'à tendreté." },
      { title: "Service", description: "Servir la tanjia bien chaude, accompagnée de pain marocain traditionnel." }
    ],
    description: "Spécialité de Marrakech, la tanjia marrakchia marie jarret de mouton et épices dans une cuisson lente pour une saveur incomparable.",
    body: [],
    featured: false,
    relatedProducts: []
  }
];
